# Generated by Django 5.0.4 on 2024-04-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('anopublicado', models.IntegerField()),
                ('status_leitura', models.CharField(choices=[('NL', 'Não Lido'), ('EL', 'Em Leitura'), ('L', 'Lido')], default='NL', max_length=2)),
                ('avaliacao', models.IntegerField(choices=[(0, '0 Estrelas'), (1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], default=0)),
                ('isbn', models.CharField(max_length=13, null=True)),
                ('in_wishlist', models.BooleanField(default=False)),
                ('in_collection', models.BooleanField(default=True)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to=settings.AUTH_USER_MODEL)),
                ('livros', models.ManyToManyField(related_name='desejado_por', to='mainapp.livro')),
            ],
        ),
    ]
