# Generated by Django 5.0.3 on 2024-03-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_name_categoria_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='genero',
        ),
    ]
