# Generated by Django 5.0.3 on 2024-04-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_categoria_categoria_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='avaliacao',
            field=models.IntegerField(choices=[(0, '0 Estrelas'), (1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], default=0),
        ),
        migrations.AddField(
            model_name='livro',
            name='status_leitura',
            field=models.CharField(choices=[('NL', 'Não Lido'), ('EL', 'Em Leitura'), ('L', 'Lido')], default='NL', max_length=2),
        ),
    ]
