# Generated by Django 5.0.4 on 2024-04-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_livro_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
