# Generated by Django 5.0.4 on 2024-04-07 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_listadesejos_livro_isbn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadesejos',
            name='nome',
        ),
        migrations.AddField(
            model_name='listadesejos',
            name='livros',
            field=models.ManyToManyField(related_name='lista_desejos', to='mainapp.livro'),
        ),
        migrations.AddField(
            model_name='listadesejos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to=settings.AUTH_USER_MODEL),
        ),
    ]
