# Generated by Django 5.0.4 on 2024-04-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_listadesejos_nome_listadesejos_livros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadesejos',
            name='livros',
            field=models.ManyToManyField(related_name='desejado_por', to='mainapp.livro'),
        ),
    ]
