# Generated by Django 5.0.4 on 2024-04-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_listadesejos_livros'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='in_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
