# Generated by Django 5.0.4 on 2024-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_bookhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhistory',
            name='status',
            field=models.CharField(choices=[('NL', 'Não Lido'), ('EL', 'Em Leitura'), ('L', 'Lido')], default='NL', max_length=2),
        ),
    ]
