# Generated by Django 5.0.4 on 2024-04-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_bookhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookhistory',
            name='status',
        ),
    ]
