# Generated by Django 5.0.4 on 2024-04-22 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_bookhistory_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadesejos',
            name='livros',
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('anopublicado', models.IntegerField()),
                ('status_leitura', models.CharField(choices=[('NL', 'Fui'), ('EL', 'Quero ir')], default='NL', max_length=2)),
                ('avaliacao', models.IntegerField(choices=[(0, '0 Estrelas'), (1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], default=0)),
                ('isbn', models.CharField(max_length=13, null=True)),
                ('in_wishlist', models.BooleanField(default=False)),
                ('in_collection', models.BooleanField(default=True)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listadesejos',
            name='cafes',
            field=models.ManyToManyField(related_name='desejado_por', to='mainapp.cafe'),
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
