# Generated by Django 5.0.4 on 2024-04-22 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_listadesejos_livros_cafe_listadesejos_cafes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookHistory',
            new_name='CoffeeHistory',
        ),
        migrations.RenameField(
            model_name='coffeehistory',
            old_name='book_title',
            new_name='coffee_title',
        ),
    ]
