# Generated by Django 5.0.4 on 2024-04-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_bookhistory_coffeehistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='status_leitura',
            new_name='status_cafeteria',
        ),
    ]
