# Generated by Django 5.0.4 on 2024-04-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_rename_status_leitura_cafe_status_cafeteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='titulo',
            new_name='nome',
        ),
    ]
