# Generated by Django 5.0.4 on 2024-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_cafe_status_cafeteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='status_cafeteria',
            field=models.CharField(choices=[('NL', 'Não Favorita'), ('EL', 'Favorita')], default='NL', max_length=2),
        ),
    ]
