# Generated by Django 5.0.4 on 2024-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_cafe_status_cafeteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='anopublicado',
            field=models.CharField(max_length=15),
        ),
    ]
