# Generated by Django 5.0.6 on 2024-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_cafe_anopublicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome1', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
