# Generated by Django 5.0.6 on 2024-05-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_listadesejoscafe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListadesejosCafe',
        ),
    ]
