# Generated by Django 5.0.6 on 2024-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_delete_franquia_remove_cafe_vezes_visitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_frequente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(0, '0 Estrelas'), (1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], null=True),
        ),
    ]
