# Generated by Django 5.0.6 on 2024-05-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_cafe_is_frequente_alter_cafe_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='autor',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='endereco',
        ),
    ]
