# Generated by Django 5.0.6 on 2024-05-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_rename_anopublicado_cafe_cntt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='genero',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='genero',
            new_name='tipo',
        ),
    ]
