# Generated by Django 5.0.4 on 2024-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_rename_genero_cafe_tipo_rename_genero_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='caracteristicas',
            field=models.TextField(blank=True),
        ),
    ]
