# Generated by Django 5.0.4 on 2024-05-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_cafe_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_favorita',
            field=models.BooleanField(default=False),
        ),
    ]
