# Generated by Django 5.0.4 on 2024-05-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_cafe_is_favorita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='is_favorita',
        ),
    ]
