# Generated by Django 5.0.4 on 2024-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_remove_cafe_is_favorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_favorita',
            field=models.BooleanField(default=False),
        ),
    ]
