# Generated by Django 5.0.6 on 2024-05-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_cafe_is_favorita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadesejos',
            name='cafes',
        ),
        migrations.RemoveField(
            model_name='listadesejos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='status_cafeteria',
        ),
        migrations.DeleteModel(
            name='CoffeeHistory',
        ),
        migrations.DeleteModel(
            name='ListaDesejos',
        ),
    ]
