# Generated by Django 5.0.6 on 2024-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_remove_listadesejos_cafes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='in_wishlist',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='tipo',
        ),
    ]
