# Generated by Django 5.0.6 on 2024-05-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_remove_cafe_in_wishlist_remove_cafe_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.categoria'),
        ),
    ]
