# Generated by Django 5.0.4 on 2024-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_cafe_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_wish',
            field=models.BooleanField(default=False),
        ),
    ]
