# Generated by Django 5.0.4 on 2024-06-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_cafe_is_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novidades', to='mainapp.cafe')),
            ],
        ),
    ]
