# Generated by Django 5.0.4 on 2024-06-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_novidade_delete_novidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='status_cafeteria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
