# Generated by Django 5.0.4 on 2024-06-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_cafe_status_cafeteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='status_cafeteria',
        ),
    ]
