# Generated by Django 5.0.4 on 2024-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_remove_cafe_status_cafeteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='endereco',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='novidade',
            old_name='endereco',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='avaliacao',
            field=models.IntegerField(choices=[(0, '0 Estrelas'), (1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], default=0),
        ),
    ]
