# Generated by Django 5.0.4 on 2024-06-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_rename_endereco_comentario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='novidade',
            old_name='usuario',
            new_name='endereco',
        ),
    ]
